# Generated by Django 4.0.5 on 2022-06-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_brrower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='brrower',
            new_name='borrower',
        ),
    ]
