# Generated by Django 4.0.5 on 2022-07-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_add_Book', 'Can add the book '), ('can_change_book', 'Can change the book '), ('can_delete_book', 'Can delete the book '))},
        ),
    ]
